query standings($filter: TeamstatsFilter!, $order: [OrderBy]) {
  teamstats(filter: $filter, orderBy: $order) {
    team {
      teamsim
    }
    games
    wins
    loss
    ties
    points
    goalsfor
    goalsagainst
    diff
    winp
    streak
  }
}
