mutation managerLogin(
  $username: String!
  $password: String!
  $refresh: Boolean
) {
  login(username: $username, password: $password, refresh: $refresh) {
    access_token
    refresh_token
  }
}
