name: 📱 Build android App and publish to Play Store

on: workflow_dispatch
jobs:
  buildNative:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          name: buildFiles
          path: android/app/build

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: 🔨 Build Project
        run: |
          cd /home/runner/work/tohl-ui/
          yarn install
          yarn generate
          npx cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: |
          cd /home/runner/work/tohl-ui/android/
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore
          ./gradlew bundleRelease --no-daemon
  publishToStore:
    runs-on: ubuntu-latest
    needs: buildNative
    steps:
      - uses: r0adkll/upload-google-play@v1
        with:
          name: buildFiles
          path: android/app/build
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.mytohl.app
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: production
