name: 📱 Build android aapp and publish to Play Store

on: workflow_dispatch
  jobs:
    buildNative:
      runs-on: ubuntu-latest
      needs: web-deploy
      steps:
        - uses: actions/checkout@v2
          with:
            name: buildFiles
            path: |
              dist
              android/app/build
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: 17
            distribution: 'adopt'
            cache: gradle
        - name: Build with Gradle
          run: |
            npx cap sync android
            cd android
            echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
            gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore
            ./gradlew bundleRelease --no-daemon
    publishToStore:
      runs-on: ubuntu-latest
      needs: buildNative
      steps:
        uses: r0adkll/upload-google-play@v1
        with:
          name: buildFiles
          path: |
            dist
            android/app/build
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.mytohl.app
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: production
