name: 📱 Build android App and publish to Play Store

on:
  push:
    branches:
      - master
jobs:
  buildNative:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🟢 Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: 🔨 Build Project
        run: |
          yarn install
          yarn generate
          npx cap sync android

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: 🐘 Build with Gradle
        env:
          VERSION_CODE: ${{ github.run_number }}
          VERSION_NAME: 'v1.${{ github.run_number }}'
          SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        run: |
          cd android
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore.jks
          ./gradlew bundleRelease --no-daemon
          pwd
      - name: 🛍 Publish to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.mytohl.app
          releaseFiles: ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
          track: production
